### ISSUE TITLE
Update pds-github-util to trigger github-actions-base to release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-github-util#21]
@nutjob4life [see this comment](https://github.com/NASA-PDS/github-actions-base/issues/10#issuecomment-900422304).

Here's an idea: make the Github Actions Base always use the _latest_ pds-github-util, **and** make pds-github-util's release trigger a build/register of Github Actions Base 😁

_Originally posted by @nutjob4life in https://github.com/NASA-PDS/github-actions-base/issues/10#issuecomment-900437695_

**Comment by jordanpadams** [comment]
@nutjob4life not sure if you will be able to squeeze this in for this sprint. we can push if needed.

**Comment by nutjob4life** [comment]
I should just keep my darn mouth shut! 😂
