### ISSUE TITLE
Potential race condition in handling of stable build and repository dispatch

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-github-util#27]
The [trigger-dependency workflow](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/trigger-dependency.yaml) was split out of `stable-cicd` in 179a3ce97dda6f38622516d775468ad3389981b3. This seems (note, it's not been tested) to create a bit of a race condition in our build pipeline.

Specifically, `trigger-dependency` runs when a new release is tagged and the repo called (`github-actions-base`) pulls the latest version of `pds-github-util` from PyPI.
```
on:
    push:
        tags:
            -  v*
```

The Roundup action publishes artifacts out prior to tagging a release on Github. See below. But any delay in the "latest" being updated on PyPI will likely result in our triggered build to pull the old version.
```
class PDSAssembly(Assembly):
    '''The PDS-flavored assembly which has 9 different steps'''
    pdsSteps = [
        StepName.unitTest,
        StepName.integrationTest,
        StepName.docs,
        StepName.build,
        StepName.artifactPublication,
        # NASA-PDS/roundup-action#29: generate the requirements before tagging the release
        StepName.requirements,
        # NASA-PDS/roundup-action#29: generate the changelog before tagging the release
        StepName.changeLog,
        StepName.githubRelease,
        StepName.docPublication,
    ]
```

Given the above, it's probably necessary to call the `repository_dispatch` after the Roundup step finishes (A.K.A, revert to the pre 179a3ce97dda6f38622516d775468ad3389981b3 state) or to delay the repository dispatch (say ... by a `sleep` call. Hat tip to @nutjob4life for that one).

Edit: Special thanks again to @nutjob4life for helping work through the above, especially in the Roundup functionality and "normal release procedures" department.

**Comment by MJJoyce** [comment]
@jordanpadams, do you have thoughts on the above with regards to the changes that were made in the referenced commit? Do we want to keep the processes split (and triggered off different events) to support a particular workflow that you had in mind?

**Comment by jordanpadams** [comment]
@MJJoyce no particular reason for splitting it out. I thought that may fix the problem we were seeing because of how it was kicking off the processes (e.g. branch name = `release/x` vs on tag. That obviously didn't work so feel free to revert the change.

**Comment by MJJoyce** [comment]
+1, sounds good. I'll revert. Thanks!
