### ISSUE TITLE
Build handling should not rely on NASA-PDS/roundup-action

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-github-util#31]
We have a bit of chicken and egg problem with `pds-github-util` using `roundup-action` for its builds when `roundup-action` depends upon `pds-github-util` to function 😃 .

We should consider de-round-up-ifying our `pds-github-util` build.

**Comment by MJJoyce** [comment]
After trying to take out a wall by banging my head against it, here's a first pass at a Roundup-less build:
https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-unstable-cicd.yaml

At the moment this triggers off a new tag push if labelled as a release candidate (`-rc*`). See here for an example build that ran clean:
https://github.com/NASA-PDS/pds-github-util/runs/3490677165?check_suite_focus=true

And the Test PyPi page:
https://test.pypi.org/project/pds-github-util/0.23.4rc8/

This general workflow is probably better suited for a stable build but I wanted to test against Test PyPI for obvious reasons. Of course, we should likely trigger off a release and not a tag being pushed in that case but I think it will largely cover our use cases.

Thoughts on the general approach @nutjob4life @jordanpadams @tloubrieu-jpl?

**Comment by jordanpadams** [comment]
@MJJoyce looks good to me. I would prefer we do the other steps as well (run tests, generate docs, requirements, changelog, etc), but not really critical since this is really an internal utility library.

As a separate note, I love the idea of eventually having release candidates built for all our software for I&T using roundup. Not really super required at the moment, but something we can have on the back burner for an intern or something.

**Comment by MJJoyce** [comment]
Hey @jordanpadams. Definitely agree on the other steps being added. If you and others aren't opposed I think doing something incremental here (just so we can get a package out the door) would be great. We're stuck in this chicken / egg problem on our builds at the moment that is rather annoying. I realize I could also just push the package manually as well though.

+1 to the RC builds for I&T stuff in the future. Sounds like a solid idea.

**Comment by jordanpadams** [comment]
@MJJoyce +1 sounds good. if @nutjob4life approves, I am go for 🚀

**Comment by nutjob4life** [comment]
I think it would be nice to demonstrate "we eat our own dogfood" but the "chicken-egg" problem is standing in the way right now.

So +1 … 🏃‍♀️!

**Comment by MJJoyce** [comment]
+1, I'll update this into a new "stable" build that triggers off a tag push and / or release and poke y'all for one final review. Then we can get an update to this out the door and hopefully stop all our builds from exploding :)
