### ISSUE TITLE
Documentation on how to tag a release using Github Actions

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-github-util#35]
## 📖 Additional Details

Still not clear how to do this?

The [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) helps push to pypi, but
* should the `stable_cicd.yaml` be removed entirely?
* does the version number need to be updated in `__init.py__` first, and if so, won't that then trigger the unstable build, which will then fail (or tag a new stable release, which is not what we want to do)?
* should the [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) also tag a release in github?

**Comment by MJJoyce** [comment]
> The [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) helps push to pypi, but
> 
> * should the `stable_cicd.yaml` be removed entirely?

No. This manual build is really only a thin wrapper around PyPI releases to address the chicken and egg problem we were running into. Nominally `stable_cicd` and `Roundup` should get used for our builds. It has waaaaay more functionality that we should leverage.

> * does the version number need to be updated in `__init.py__` first, and if so, won't that then #trigger the unstable build, which will then fail (or tag a new stable release, which is not what we want to do)?

Yes to both. However, if you're using this the builds should already be broken so it doesn't matter much if another one gets triggered.

> * should the [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) also tag a release in github?

Ideally it would do everything that `Roundup` does without using `Roundup` (avoiding that whole chicken and egg problem). In its current form the workflow would be something on the order of:

- Manually update version and tag new release locally. Push to `origin`
- Manually create release on GitHub
- Run the manual build to push to PyPI.

It's just saving you from running the build / dealing with credentials / pushing to PyPI. We could duplicate some / all of the Roundup functionality in this build but it's a non-zero amount of work for a build that (hopefully) will get run very very rarely. The original intention was to completely strip out the Roundup build eventually but it just doesn't seem worth the effort. At worst, we'll run into this "pds-github-util bug is breaking Roundup so I can't build pds-github-util" problem again and need to fix / semi-manually release and push the package.

**Comment by MJJoyce** [comment]
Also, @nutjob4life ran this manual process the other day so he might have some insight or thoughts on it.

**Comment by jordanpadams** [comment]
@MJJoyce sorry. i jumped the gun here and [removed the stable CICD](https://github.com/NASA-PDS/pds-github-util/commit/5e98e71ce3cbf468713a069e1a0b6a617444fb3b) because it [doesn't stop failing](https://github.com/NASA-PDS/pds-github-util/actions/runs/1214916238). we can re-add once we think it works :-)

**Comment by jordanpadams** [comment]
> > The [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) helps push to pypi, but
> > 
> > * should the `stable_cicd.yaml` be removed entirely?
> 
> No. This manual build is really only a thin wrapper around PyPI releases to address the chicken and egg problem we were running into. Nominally `stable_cicd` and `Roundup` should get used for our builds. It has waaaaay more functionality that we should leverage.
> 
> > * does the version number need to be updated in `__init.py__` first, and if so, won't that then #trigger the unstable build, which will then fail (or tag a new stable release, which is not what we want to do)?
> 
> Yes to both. However, if you're using this the builds should already be broken so it doesn't matter much if another one gets triggered.
> 
> > * should the [existing manual trigger](https://github.com/NASA-PDS/pds-github-util/blob/main/.github/workflows/squaredown-stable.yaml) also tag a release in github?
> 
> Ideally it would do everything that `Roundup` does without using `Roundup` (avoiding that whole chicken and egg problem). In its current form the workflow would be something on the order of:
> 
> * Manually update version and tag new release locally. Push to `origin`
> * Manually create release on GitHub
> * Run the manual build to push to PyPI.
> 
> It's just saving you from running the build / dealing with credentials / pushing to PyPI. We could duplicate some / all of the Roundup functionality in this build but it's a non-zero amount of work for a build that (hopefully) will get run very very rarely. The original intention was to completely strip out the Roundup build eventually but it just doesn't seem worth the effort. At worst, we'll run into this "pds-github-util bug is breaking Roundup so I can't build pds-github-util" problem again and need to fix / semi-manually release and push the package.

copy. adding stable CICD back to see if things "work"

**Comment by MJJoyce** [comment]
:+1: I'll take a look at why it's breaking in a bit. Working on updating Roundup stuff ATM.

**Comment by jordanpadams** [comment]
Closing per 5b97854
