### ISSUE TITLE
python_snapshot_release and version / tag handling isn't cooperating

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-github-util#36]
## 🐛 Describe the bug
Our [unstable Roundup build is unstable](nasa-pds/roundup-action/issues/52). This seems to be a result of our python snapshot release process utility here in `pds-github-util`. Consider the following:

1. Roundup executes it's [Github Release Step](https://github.com/NASA-PDS/roundup-action/blob/main/src/pds/roundup/_python.py#L99) for our unstable build. This calls down to `pds-github-util`'s [python_snapshot_release](https://github.com/NASA-PDS/pds-github-util/blob/main/pds_github_util/release/python_snapshot_release.py).
2. This calls out to our [release_publication](https://github.com/NASA-PDS/pds-github-util/blob/main/pds_github_util/release/release.py#L75) utility configured to "expect" a `-dev` suffix on our snapshot release.
3. `release_publication` then checks the release version that it "finds" against the suffix to determine if this is a snapshot release or not.

        delete_snapshot_releases(repo, suffix)
        if tag_name.endswith(suffix):
            create_snapshot_release(repo, repo_name, "main", tag_name, tagger, upload_assets)
        else:
            create_release(repo, repo_name, "main", tag_name, tagger, upload_assets)

## 🕵️ Expected behavior
We should tag a snapshot release when we say to do that :)

## 🩺 Test Data / Additional context
See the unstable build is unstable ticket for a link to a breaking build

---

## ⚙️ Engineering Details
The logic in `release_publication` seems both unnecessary and faulty. We're calling into `release_publication` with information on whether we do or don't want a snapshot release. Additionally, the logic for determining this is dependent upon the version that we extract with other tooling. In the case of a `versioneer` version this isn't ever going to have the expected suffix. A kwarg such as `snapshot=False` seems like a better way of specifying if we do or don't want a snapshot release instead of trying to automatically figure it out.

**Comment by MJJoyce** [comment]
@nutjob4life, if you have the time to sanity check what I have above and make sure I'm not missing out on some key detail of why this is as it is I would super appreciate it.

**Comment by nutjob4life** [comment]
Yeah I think you got it.

When @tloubrieu-jpl initially developed `pds-github-util` I think the idea was to treat Python projects like Java projects. But then we added Versioneer and Python projects started looking quite a bit different from Java.

The `pds-github-util` package installs two executables: `python-release` and `python-snapshot-release`. They're the exact same thing, although you'd expect one to use the `argv[0]` trick to tell how it's being invoked and act differently. While you're here, let's dump `python-snapshot-release` and use an explicit flag to indicate a snapshot release.

After all, part of the `import this` Python philosophy: explicit > implicit.
