### ISSUE TITLE
Versions seem to be not incrementing correctly for python unstable releases

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-github-util#48]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/pds-template-repo-python/releases/tag/v8.0.1-SNAPSHOT 

This should probably be 1.1.0-SNAPSHOT or something like that?

**Comment by jordanpadams** [comment]
@MJJoyce and @nutjob4life not sure which one of you have a chance to poke at this

**Comment by MJJoyce** [comment]
This is likely going to be related to https://github.com/NASA-PDS/roundup-action/issues/69 as well.
