### ISSUE TITLE
RDD contains issues marked as wontfix

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-github-util#51]
## 🐛 Describe the bug

Looking at the RDD, ttps://github.com/NASA-PDS/validate/issues/314 should not be included as it was tagged as `wontfix`

## 📜 To Reproduce
See https://nasa-pds.github.io/releases/12.0/rdd.html#id178 and testing completed for the issue here: https://github.com/NASA-PDS/validate/issues/314#issuecomment-951528790 

## 🕵️ Expected behavior

issues tagged with `invalid`, `wontfix`, or `duplicate` do not appear in RDD

Should be updated in https://github.com/NASA-PDS/pds-github-util/pull/39

**Comment by tloubrieu-jpl** [comment]
@jordanpadams The RDD is updated https://nasa-pds.github.io/releases/12.0/rdd.html#validate

Pull request https://github.com/NASA-PDS/pds-github-util/pull/39 is ready for review and merge !
