### ISSUE TITLE
Upgrade RDD generation (summaries) for build 13.1

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-github-util#69]
## 💡 Description

- [ ] Fix weird links, see screenshot 

![image](https://user-images.githubusercontent.com/60993872/202359366-ca616777-935c-4fe5-a25b-2d927a4fa19d.png)

TO BE COMPLETED

**Comment by tloubrieu-jpl** [comment]
@jimmie can you complete this ticket with the things you had to edit manually in the RDD for build 13.0. We'll try to fix it before build 13.1

**Comment by jordanpadams** [comment]
I think this was fixed either here: https://github.com/NASA-PDS/pds-github-util/pull/67 or in the updates per support for I&T (v0.27.0+)
