### ISSUE TITLE
As a PDS software user, I want to have a hierarchical view of the PDS EN components that apply to my user interests

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-github-util#7]
## Motivation
...so that I can first see the application I can install/use and if I want to dig deeper, I can find the components (libraries, services) on which the application is build.

## Additional Details
That would be an upgrade of the current build summary view which is flat https://nasa-pds.github.io/releases/11.1/index.html

## Acceptance Criteria
**Given** A PDS build (e.g. 11.1)
**When I perform** When I get the build summary (https://nasa-pds.github.io/releases/11.1/index.html)
**Then I expect** I expect to see only user facing application (ie not the internal libraries components or back end service software)

**Given** A PDS build (e.g. 11.1)
**When I perform** When I get the description of an application (e.g. pds-registry-app)
**Then I expect** I expect to see links to the different components which contribute to the implementation (e.g. harvest, registry-mgr, api)

## Engineering Details
Application/library relationships that will be stored in the maven pom or python requirements.txt/setup file, in micro-service architecture components, that would be in a deployment configuration file (e.g terraform or docker-compose). Ideally I would like pds-github-util to be able to use that to aggregate components into applications.

@jordanpadams' design notes:
my thoughts on the split on the build summaries:
* Tools - PLAID, MILabel, Validate, LDDTool,  PDSView, Transform (ignore PLAID right now since it needs an upgrade)
* Libraries - PDS4 JParser
* Core Tools and Services - all remaining components

this is a stop-gap for now. ideally, we should probably figure out the best way to replace https://pds.nasa.gov/tools/about/ with our build summaries page or something else. some thoughts on that (including some tools not under NASA-PDS):
* data design and validate tools - PLAID, MILabel, Validate, LDDTool
* data users - PDSView, Transform, GDAL
* libraries - PDS4 JParser, PDS4 Tools (SBN pds4_tools)
* discipline node services - Registry App
* core tools and services - all remaining components

**Comment by jordanpadams** [comment]
@tloubrieu-jpl see **Engineering Details** for some thoughts on sections for the software summaries

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I updated the build summaries with the categories you requested : https://nasa-pds.github.io/releases/releases.html

**Comment by jordanpadams** [comment]
+1 @tloubrieu-jpl

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can you checkout the changes i've proposed on pds-github-util and on the docs? i think I broke something (again), but we can chat about the groupings later if you'd like.

i thought we should put all things together that users or the nodes will use very clearly.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams that sounds good, I reviewed your pull request earlier today, see https://github.com/NASA-PDS/pds-github-util/pull/10/files
