### ISSUE TITLE
Refactor github-util Into Smaller Subpackages

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-github-util#72]
## 💡 Description

The dependencies are running into conflicts we want to split the package into smaller packages (To Be Defined).

I guess the code would stay in the same repository but I am not sure about that.

**Comment by jordanpadams** [comment]
📆 June status: Underway. On schedule.

**Comment by jordanpadams** [comment]
Breakup completed. Some additional follow-on tasks in work.
