### ISSUE TITLE
Refactor the package into various separate components

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-github-util#74]
## 💡 Description

As decided in ticket https://github.com/NASA-PDS/pds-github-util/issues/73

Split the current package into:
- [x] Releasers: `snapshot-release`, `maven-release`, `python-release`
- [x] Requirements reporting: `requirement-report`
- [x] Release reporting: `git-ping`, `summaries`, `pds-plan`
- [x] Issue handling: `pds-issues`, `move-issues`, `milestones`, `pds-labels`
- [X] ~LDD: `ldd-release`~

**Comment by nutjob4life** [comment]
I think they should be in separate repositories. Yes, we have a _ton_ of them already—and I trust some day GitHub will offer a _folder_ feature—but I can foresee that the [logical groupings](https://github.com/NASA-PDS/pds-github-util/issues/73) we've come up with may also have unique automation needs in terms of GitHub Actions Workflows, code quality reporting, code owners, etc.

**Comment by tloubrieu-jpl** [comment]
Hi Sean, before github provides the folder feature, we could have a common prefix for all this repositories. That is what we to for registry or doi applications.
I don't know what the prefix for these routines would be.  I remember Jordan had an application named 'conman' which was the ancestor of github util ? We could look into the cow-boy lexicon for that as well. I also heard that chatGPT is good at finding names. I tried: can you propose a name for utility command line tool in the cow-boy lexicon ? It found 'lariat'.

**Comment by tloubrieu-jpl** [comment]
By clicking the regenarate response in chatGPT, I also got: `wrangler` and `lasso`.

**Comment by nutjob4life** [comment]
Prefixes yes … and Western theme yes!

**Comment by jordanpadams** [comment]
ldd-release has already been refactored out per https://github.com/NASA-PDS/pds-github-util/pull/75

**Comment by jordanpadams** [comment]
@nutjob4life ☝️

**Comment by nutjob4life** [comment]
There are no pull requests for this since these are all new repositories. Please see the following:

- https://github.com/NASA-PDS/lasso-issues
- https://github.com/NASA-PDS/lasso-releasers
- https://github.com/NASA-PDS/lasso-reports
- https://github.com/NASA-PDS/lasso-requirements

**Comment by tloubrieu-jpl** [comment]
Someone need to look at the new repository to validate this ticket.

**Comment by jordanpadams** [comment]
Calling this good. Used repos for numerous other activities
